### ISSUE TITLE
'Acre' after number word

### ISSUE THREAD

**Issue by ifpingram** [ifp/text#1]
LAKE, a five acre lake set in 8 acres of rolling countryside with great views and 140lbs catfish. 

=>

Lake, a Five **acre** Lake Set in 8 Acres of Rolling Countryside with Great Views and 140lbs Catfish.

==

The acre in bold should be Capitalised

**Comment by andzandz** [comment]
Fixed, and merged into master.

Abbreviations are lowercase, full unit words are Uppercase (e.g. mins, Minutes, km, Kilometres)
